[[session]]
name = "misc"
path = "~"

[[session]]
name = "runner"
path = "~/Code/Wilderborn/cms"
# startup_command = "nvim -c ':Telescope git_files'"

[[session]]
name = "tmux-config"
path = "~/.dotfiles/tmux"
startup_command = "nvim -O tmux.conf sesh.toml"
